### ISSUE TITLE
Reverse binary operator overload

### ISSUE THREAD

**Issue by amelentev** [amelentev/java-oo#25]
Use case - multiply double to Complex:

    Complex a = new Complex(1.2, 2.3)
    1.2*a

We can't add method `multiply` to double.

Solution:
add method `Complex#multiplyRev(double)`
This method will be used on second operand in cases where is no multiply method in left operand.
So: `1.2 * a` will be transformed to `a.multiplyRev(1.2)`
This should work for every binary operator.

**Comment by yuemingl** [comment]
That's really useful!

**Comment by amelentev** [comment]
Implemented in eclipse-oo-plugin 0.5
