### ISSUE TITLE
JSR: Compiler Extensions

### ISSUE THREAD

**Issue by sirinath** [amelentev/java-oo#30]
Is it possible to see if you can get the extension mechanism into the main stream? Perhaps a JSR.

This is amazing and cool.

**Comment by sirinath** [comment]
Also not fear of breaking internal changes then.

**Comment by amelentev** [comment]
There is a new compiler plug-in mechanism in JDK8:
http://docs.oracle.com/javase/8/docs/jdk/api/javac/tree/com/sun/source/util/Plugin.html
http://techbitsfromsridhar.blogspot.ru/2013/02/java-compiler-plug-ins-in-java-8-use.html
I'm not using it yet.
