### ISSUE TITLE
Java Operator Overloading not working on Netbeans 8.0.2

### ISSUE THREAD

**Issue by deltasquad451** [amelentev/java-oo#33]
with netbeans 8.0.2 with JDK 8 and the javac8-oo-plugin-0.1.1.jar I can build the code, but I can't run due to a "bad operand type" error:
![capture](https://cloud.githubusercontent.com/assets/5035101/8895286/15625d64-3389-11e5-9528-c56d3df5caca.PNG)

**Comment by amelentev** [comment]
dublicate of #15
