### ISSUE TITLE
IntelliJ plugin 0.4.1 does not support Java 8u51

### ISSUE THREAD

**Issue by josueetcom** [amelentev/java-oo#34]
I love the idea of what the plugin could do (Great paper!). Unfortunately I'm unable to use it:

<img width="441" alt="screen shot 2015-07-26 at 3 14 41 pm" src="https://cloud.githubusercontent.com/assets/8023233/8896184/134f142a-33a9-11e5-84d6-a878564589cf.png">

If you know of any way to resolve this or what Java 8 version to use instead I'd like to know. Thanks

**Comment by amelentev** [comment]
Probably you are running Android Studio on JRE6 (Mac?). 51.0 is JRE7.
Try to run Android Studio on JRE/JDK 7 or 8.

**Comment by josueetcom** [comment]
Do you mean the JRE running Android Studio the IDE itself? Because the project is using compileOptions of Java 8

**Comment by amelentev** [comment]
Yes. The plugin runs in the IDE JVM process, not project's.
See 'IDE JDK' at http://tools.android.com/tech-docs/configuration/osx-jdk

**Comment by josueetcom** [comment]
Awesome! Exporting STUDIO_SDK to be the most updated jvm works! Thanks man, the plugin is awesome!
