### ISSUE TITLE
IDE plugin versioning - documentation

### ISSUE THREAD

**Issue by binkley** [amelentev/java-oo#35]
Hi,

Really a question more than an issue - that the IntelliJ plugin is 0.4.1 but the others are 0.5 ... does this mean IntelliJ is behind the others, or does it mean they use different version sequences?

A comment in the README about this would help or an FAQ.

Cheers,
Brian

**Comment by amelentev** [comment]
Comment added. Thanks.
`Note plugin versions are independant. If version for X > version for Y then it doesn't mean Y is behind featurewise.`
