### ISSUE TITLE
Plugin disables ability show error markers in editor

### ISSUE THREAD

**Issue by saaadel** [amelentev/java-oo#37]
This Plugin disables ability to show error markers in editor (curves and marker on right scroll bar).
Errors still persist on messages tool window.

For example, following code does not show error markers in editor:
System.out.print123ln("abc");

IDEA 15.0.2
Windows10x64

**Comment by saaadel** [comment]
Tested on Java operator overloading support v0.4.1

**Comment by amelentev** [comment]
dublicate of #36

**Comment by amelentev** [comment]
Fixed in idea-oo-0.5. Please update/reinstall plugin from repository.
