### ISSUE TITLE
Problems compiling in Intellij IDEA 2016.1.3 Ult

### ISSUE THREAD

**Issue by lilggamegenuis** [amelentev/java-oo#39]
Hi, i have just started using Java-OO and so far nothing is working. Everywhere i try to use any of the operators, the compiler throws errors while the IDE says that everything is fine. I have tried using the idea plugin as well as the javac plugin and it hasn't worked. I'm not sure what files to upload so if you need any, i can upload them. Hope i can get this working.

**Comment by amelentev** [comment]
Idea plugin should be used *with* javac plugin. and seems javac plugin doesn't work in your case.
try open `javac-oo-mvndemo` project in IDEA: https://github.com/amelentev/java-oo/tree/master/javac-oo-mvndemo
Works for me in IDEA 2016.2

**Comment by lilggamegenuis** [comment]
OK, when i used the maven demo it worked fine, but when i tried in my project it threw out errors (like this: java: array required, but java.util.ArrayList<java.lang.String> found). For my project i used the javac8 plugin since i'm using java 8. Although when i tried this time i got a lombok error (my main lib i use, uses it). Is there a possibility that its incompatible?

**Comment by amelentev** [comment]
I installed lombok plugin in IDEA 2016.2 and added lombok.jar to pom.xml
`@Getter @Setter` works for me in javac-oo-mvndemo.
Check you use javac compiler at `Settings`-..-`Java Compiler`. And annotation processing is enabled in `Annotation Processors`
Maybe you are using some other special settings in IDEA or javac.
If you construct a small example project what doesn't work well, I can look into it.

**Comment by lilggamegenuis** [comment]
Sorry about being so late with this. It was my mistake.
