### ISSUE TITLE
Cannot compile in IntelliJ IDEA Ultimate 2016.3.3

### ISSUE THREAD

**Issue by andrehsu** [amelentev/java-oo#42]
I am using the javac compiler, annotation processing is enabled, and I have installed the plugin, and also added the library. However, I get this error:

Error:java: java.lang.IllegalArgumentException: Can not set com.sun.tools.javac.api.MultiTaskListener field com.sun.tools.javac.main.JavaCompiler.taskListener to javaoo.javac.OOProcessor$WaitAnalyzeTaskListener

**Comment by yuemingl** [comment]
I can repeat the error in IntelliJ IDEA 15.04

**Comment by yuemingl** [comment]
The same error in IntelliJ IDEA Ultimate 2016.1

Information:Using javac 1.8.0_73 to compile java sources
Information:java: Injecting OO to javac
Information:1/26/17, 4:33 PM - Compilation completed with 1 error and 0 warnings in 857ms
Error:java: java.lang.IllegalArgumentException: Can not set com.sun.tools.javac.api.MultiTaskListener field com.sun.tools.javac.main.JavaCompiler.taskListener to javaoo.javac.OOProcessor$WaitAnalyzeTaskListener

**Comment by amelentev** [comment]
This is because you use plugin for java7 on JDK8.
Use `javac8-oo-plugin` instead: http://amelentev.github.io/mvnrepo/java-oo/javac8-oo-plugin/0.5/javac8-oo-plugin-0.5.jar
