### ISSUE TITLE
"---" operator in Java 8

### ISSUE THREAD

**Issue by StefanLobbenmeier** [amelentev/java-oo#61]
I found the "---" operator in the code. I can not find documentation for it. Can someone explain?
https://github.com/amelentev/java-oo/blob/ea44e927c01d8d228c7e193ceda7b4735eceb584/javac-oo-plugin/src/main/java/javaoo/OOMethods.java#L41

**Comment by amelentev** [comment]
As I remember it is just jdk8 internal representation of usual unary minus "-", to separate it from binary minus. So it is the same unary minus.

**Comment by StefanLobbenmeier** [comment]
Thank you very much!
