### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by TiMauzi** [amelentev/java-oo#67]
Using Intellij IDEA 2020.3.2 (Ultimate), I followed the instructions given for [Intellij IDEA IDE](https://github.com/amelentev/java-oo#intellij-idea-ide) on a fresh test project, using the `javac8-oo-plugin-0.5.jar`. I copy-pasted the [example](https://github.com/amelentev/java-oo#java-operator-overloading) into a fresh class `Test.java`.

When I try compiling (using Java 15.0.1), the following exception appears:
```
java: java.lang.ClassCastException: class com.sun.proxy.$Proxy21 cannot be cast to class com.sun.tools.javac.processing.JavacProcessingEnvironment (com.sun.proxy.$Proxy21 is in unnamed module of loader java.net.URLClassLoader @2ff4acd0; com.sun.tools.javac.processing.JavacProcessingEnvironment is in module jdk.compiler of loader 'app')
```
What may be gone wrong?

**Comment by amelentev** [comment]
You need to use the java **8** compiler. There is no support for java versions above 8.

**Comment by amelentev** [comment]
#59
